language: go
go:
- 1.8.x

sudo: false

install:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    go get ./...;
  fi

script:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    make test;
  fi

after_success:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    curl -sL https://git.io/goreleaser | bash;
  fi

notifications:
  email: false
