name: Build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -v

      - name: Run Tests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash ./test.sh
          bash <(curl -s https://codecov.io/bash)

      - name: Build Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref != 'refs/heads/master'
        run: |
          curl -sL https://git.io/goreleaser | bash;
